const mongoose = require('mongoose')
const recipeSchema = new mongoose.Schema({
    name: String,
    description: String,
    image: String,
    course: String,
    one_pot: Boolean,
    sheet_pan: Boolean,
    quick_and_easy: Boolean,
    limited_ingredients: Boolean,
    prep_time: { type:Number, min: 0},
    cook_time: { type:Number, min: 0},
    ingredient_1: String,
    ingredient_1_quantity: String,
    ingredient_1_measurement: String,
    ingredient_2: String,
    ingredient_2_quantity: String,
    ingredient_2_measurement: String,
    ingredient_3: String,
    ingredient_3_quantity: String,
    ingredient_3_measurement: String,
    ingredient_4: String,
    ingredient_4_quantity: String,
    ingredient_4_measurement: String,
    ingredient_5: String,
    ingredient_5_quantity: String,
    ingredient_5_measurement: String,
    ingredient_6: String,
    ingredient_6_quantity: String,
    ingredient_6_measurement: String,
    ingredient_7: String,
    ingredient_7_quantity: String,
    ingredient_7_measurement: String,
    ingredient_8: String,
    ingredient_8_quantity: String,
    ingredient_8_measurement: String,
    ingredient_9: String,
    ingredient_9_quantity: String,
    ingredient_9_measurement: String,
    ingredient_10: String,
    ingredient_10_quantity: String,
    ingredient_10_measurement: String,
    instruction_1_name: String,
    instruction_1_description: String,
    instruction_2_name: String,
    instruction_2_description: String,
    instruction_3_name: String,
    instruction_3_description: String,
    instruction_4_name: String,
    instruction_4_description: String,
    instruction_5_name: String,
    instruction_5_description: String,
    instruction_6_name: String,
    instruction_6_description: String,
    instruction_7_name: String,
    instruction_7_description: String,
    instruction_8_name: String,
    instruction_8_description: String,
    instruction_9_name: String,
    instruction_9_description: String,
    instruction_10_name: String,
    instruction_10_description: String,
    notes: String
    
})
const Recipe = mongoose.model('Recipe', recipeSchema)

module.exports = Recipe

