module.exports = [
    {
        name: 'Japanese Curry',
        description: 'Test Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/japanese-curry.jpg',
        course: 'Dinner',
        one_pot: true,
        prep_time: 15,
        cook_time: 40,
        ingredient_1: 'Chicken Thighs',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'Pound',
        ingredient_2: 'Carrots',
        ingredient_2_quantity: '3',
        ingredient_2_measurement: 'Whole',
        ingredient_3: 'Yellow Onion',
        ingredient_3_quantity: '1',
        ingredient_3_measurement: 'Whole',
        ingredient_4: 'Yukon Gold Potatoes',
        ingredient_4_quantity: '1',
        ingredient_4_measurement: 'Pound',
        ingredient_5: 'Ginger',
        ingredient_5_quantity: '2',
        ingredient_5_measurement: 'Inch Piece',
        ingredient_6: 'Garlic',
        ingredient_6_quantity: '6',
        ingredient_6_measurement: 'Cloves',
        ingredient_7: 'Apple',
        ingredient_7_quantity: '1',
        ingredient_7_measurement: 'Whole',
        ingredient_8: 'Unsalted Butter',
        ingredient_8_quantity: '1/2',
        ingredient_8_measurement: 'Cup',
        ingredient_9: 'All-purpose Flour',
        ingredient_9_quantity: '1/2',
        ingredient_9_measurement: 'Cup',
        ingredient_11: 'Chicken Stock',
        ingredient_11_quantity: '1',
        ingredient_11_measurement: 'Quart',
        ingredient_12: 'Japanese Curry Spice Blend',
        ingredient_12_quantity: '6',
        ingredient_12_measurement: 'Tablespoons',
        instruction_1_description: 'Season chicken with salt and pepper. In a large Dutch oven, heat butter over medium-high heat until shimmering. Add chicken and cook, turning, until browned on both sides.',
        instruction_2_description: 'Add onion and cook stirring until translucent.',
        instruction_3_description: 'Add ginger and garlic and cook until fragrent',
        instruction_4_description: 'Add curry spice blend and bloom for ~ 1 minute',
        instruction_5_description: 'Add flour and stir for ~ 1 minute',
        instruction_6_description: 'Stir in chicken stock',
        instruction_7_description: 'Add back chicken, potatoes, carrots, and apple and gently simmer until potatoes and carrots are tender',
        instruction_8_description: 'Add in frozen peas and stir in for a couple of minutes',
        instruction_9_description: 'Adjust salte to taste',

    },
    {
        name: 'Avacado Toast With Egg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/avacado-toast-with-egg.jpg',
        course: 'Breakfast',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Bacon Egg and Cheese Biscuit',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/bacon-egg-cheese-sandwich.jpg',
        course: 'Breakfast',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Banh Mi',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/banh-mi.jpg',
        course: 'Lunch',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Berry Smoothie',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/berry-smoothie.jpg',
        course: 'Snack',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Bibimbap',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/bibimbap.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Bulgogi',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/bulgogi.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Chicken Soup',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/chicken-soup.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Fried Rice',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/fried-rice.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Grilled Salmon',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/grilled-salmon.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Gyoza',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/gyoza.jpg',
        course: 'Snack',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Kimbap',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/kimbap.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Ramen',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/ramen.jpg',
        course: 'Dinner',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Greek Salad',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/salad.jpg',
        course: 'Lunch',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Samosas',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/samosa.jpg',
        course: 'Snack',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
    {
        name: 'Squash Soup',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        image: '/images/soup.jpg',
        course: 'Lunch',
        prep_time: 10,
        cook_time: 20,
        ingredient_1: 'pharetra',
        ingredient_1_quantity: '1',
        ingredient_1_measurement: 'iaculis',
        ingredient_2: 'pharetra',
        ingredient_2_quantity: '2',
        ingredient_2_measurement: 'iaculis',
        ingredient_3: 'pharetra',
        ingredient_3_quantity: '1/2',
        ingredient_3_measurement: 'iaculis',
        ingredient_4: 'pharetra',
        ingredient_4_quantity: '2',
        ingredient_4_measurement: 'iaculis',
        ingredient_5: 'pharetra',
        ingredient_5_quantity: '5',
        ingredient_5_measurement: 'iaculis',
        ingredient_10_quantity: '1',
        ingredient_10_measurement: 'Quart',
        instruction_1_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. A lacus vestibulum sed arcu non odio euismod lacinia at. Ut consequat semper viverra nam libero justo laoreet. Urna porttitor rhoncus dolor purus non enim praesent. Id aliquet lectus proin nibh nisl condimentum.',
        instruction_2_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus mattis rhoncus urna neque viverra. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.',
        instruction_3_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget nullam non nisi est sit amet facilisis magna. Porttitor leo a diam sollicitudin.',
        instruction_4_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit tellus mauris a diam maecenas sed enim ut. Ridiculus mus mauris vitae ultricies leo integer malesuada. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget.',
        instruction_5_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue.',

    },
]